import mongoose from 'mongoose';

/**
 * DailySummary — M4 model.
 * One document per day. Generated by AI from that day's notes.
 * // M4: aggregate tasks for daily summary
 */
const dailySummarySchema = new mongoose.Schema({
  date: {
    type: Date,
    required: true,
    unique: true, // one per day
    index: true,
  },
  // Issue counts
  totalIssues:       { type: Number, default: 0 },
  staffingIssues:    { type: Number, default: 0 },
  costRisks:         { type: Number, default: 0 },
  maintenanceIssues: { type: Number, default: 0 },
  otherIssues:       { type: Number, default: 0 },
  // Task counts
  totalTasks:     { type: Number, default: 0 },
  completedTasks: { type: Number, default: 0 },
  // AI generated content
  keyConcerns:        [{ type: String }],
  recommendedActions: [{ type: String }],
  // Source tracking
  rawNoteIds: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Note' }],
  generatedAt: { type: Date, default: Date.now },
}, {
  timestamps: true,
});

export default mongoose.models.DailySummary || mongoose.model('DailySummary', dailySummarySchema);
